(function(){if(typeof window.CustomEvent==="function")return false;function CustomEvent(event,params){params=params||{bubbles:false,cancelable:false,detail:undefined};var evt=document.createEvent("CustomEvent");evt.initCustomEvent(event,params.bubbles,params.cancelable,params.detail);return evt}CustomEvent.prototype=window.Event.prototype;window.CustomEvent=CustomEvent})();
setTimeout(function(){if(window.jQuery!=undefined)loadWidgets();else{element=document.createElement("script");element.setAttribute("type","text/javascript");element.setAttribute("src","https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js");document.getElementsByTagName("head")[0].appendChild(element);element.onload=function(){jQuery.noConflict();loadWidgets()}}});
function loadWidgets(){jQuery(function($){var widgets=$("[data-widget]");if(widgets.length)$("[data-widget]").each(function(index,elem){var params=null;if($(elem).attr("data-widget")){params={};$.each(elem.attributes,function(i,attrib){if(attrib.name.match(/data-.+/))params[attrib.name.substr(5)]=attrib.value})}loadWidget(elem,params)});else if(typeof loadWidgetsManual==="function")loadWidgetsManual()})}
function loadWidget(elem,params){var $=jQuery;element=$(elem);var thisScript=$('script[src*="widget-loader.js"]').attr("src");var thisDomain=thisScript.match(/(([^:]*:)?\/\/[^\/]*)(\/.*)?/);if(thisDomain){thisDomain=thisDomain[1];var widgetResourceUrl=thisDomain+"/widgets/"+params["widget"]+".js?callback=?";$.getJSON(widgetResourceUrl,params,function(widgetSpecs){(new Widget(element,widgetSpecs,$)).loadStyleSheets()})}}function destroyWidget(elem){var $=jQuery;element=$(elem);element.remove()}
function Widget(loadElement,specs,$){this.specs=specs;this.slug=specs.slug;this.angularModules=specs.config.angular_modules||[];this.loadElement=loadElement;this.widgetElement=null;this.renderTemplate=function(){var html=this.specs.config.html;this.widgetElement=$('<div class="rh" style="visibility:hidden"><div class="rh-widget '+this.slug+'">'+html+"</div></div>");this.loadElement.replaceWith(this.widgetElement)};this.loadStyleSheets=function(){var styles=this.specs.config.css;if(styles){this.resetCss();
var promises=styles.map(function(style){if(style.source)return addCssRef(style.source);if(style.styles)addInlineStyles(style.styles);return true});$.when.apply($,promises).then(function(){this.load()}.bind(this))}else this.load()};this.load=function(){this.renderTemplate();this.loadScripts()};this.resetCss=function(){var cssPrefix=".rh";var resetString="html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,cite,code,del,dfn,em,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,center,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,details,embed,figure,figcaption,footer,header,hgroup,menu,nav,output,ruby,section,summary,time,mark,audio,video{margin:0;padding:0;border:0;font-size:100%;font-family:inherit;box-sizing:content-box;}article,aside,details,figcaption,figure,footer,header,hgroup,menu,nav,section{display:block}.rh-widget{overflow:visible;line-height:1;text-align:left;}ol,ul{list-style:none}blockquote,q{quotes:none}blockquote:before,blockquote:after,q:before,q:after{content:'';content:none}table{border-collapse:collapse;border-spacing:0}th,td{vertical-align:middle}";
var customResets=".bootstrap .tab-content{overflow:visible;}.ratehub-calc table>tbody>tr>td{border:0;vertical-align:middle;}";var css=(resetString+customResets).replace(/(.+?)(,|(?:{.*?}))/g,cssPrefix+" $1$2");addInlineStyles(css,"widget-reset")};this.loadScripts=function(){var jsConfig=this.specs.config.js;if(jsConfig){var getGroup=function(object){if(object.options){if(object.options.before)return"before";if(object.options.first)return"first";if(object.options.after)return"after"}return"none"};
var groups=["before","first","none","after"];var groupedScripts=groups.map(function(group){var grouped=jsConfig.filter(function(object){return getGroup(object)==group});grouped.group=group;return grouped});this.asynchronouslyLoadScripts(groupedScripts,0)}};this.asynchronouslyLoadScripts=function(groupedScripts,currentIndex){var scripts=groupedScripts[currentIndex];if(currentIndex===2){ElementQueries.init(this.specs.config.element_queries);angular.bootstrap(this.widgetElement,this.angularModules);
this.adjustLinks()}if(scripts){var promises=scripts.map(function(script,i){if(script.options&&script.options.loaded&&eval(script.options.loaded))return true;if(script.source){if(script.options&&script.options.depends)script.depends=scripts[i-1].promise;script.promise=registerScriptRef(script.source,undefined,undefined,script.depends);return script.promise}if(script.script){script.script+="\n//# sourceURL="+scripts.group+"_"+(script.id||i)+".js";eval(script.script)}return true});$.when.apply($,promises).then(function(){this.asynchronouslyLoadScripts(groupedScripts,
++currentIndex)}.bind(this))}else{$(document.body).trigger("ratehub.widget.loaded",[{widget:this.slug,element:this.widgetElement}]);document.body.dispatchEvent(new CustomEvent("ratehub.widget.loaded",{detail:{widget:this.slug,element:this.widgetElement}}));setTimeout(function(){this.widgetElement.css("visibility","visible")}.bind(this))}};this.adjustLinks=function(){if(ratehub.user.aff_info){var rootElement=this.widgetElement.parent();rootElement.find("a[href]").each(function(i,a){var href=a.href;
if(href.indexOf(ratehub.serverUri)===0&&href.indexOf("#")===-1)a.href=appendQueryParams(href,ratehub.user.aff_info)});var affInfo=ratehub.user.aff_info;var impressionHref="https://ratehub.go2cloud.org/aff_i?offer_id="+affInfo.offer_id;if(affInfo.file_id)impressionHref+="&file_id="+affInfo.file_id;impressionHref+="&aff_id="+affInfo.aff_id;if(!$("img[src='"+impressionHref+"']").length)rootElement.append('<img src="'+impressionHref+'" width="1" height="1" />')}};function registerScriptRef(src,appendTo,
id,depends){var script_tag=document.createElement("script");script_tag.setAttribute("type","text/javascript");script_tag.setAttribute("src",src);script_tag.setAttribute("charset","utf-8");if(id)script_tag.setAttribute("id",id);var deferred=$.Deferred();script_tag.onload=function(){deferred.resolve()};function appendScript(){if(appendTo)appendTo.appendChild(script_tag);else document.body.appendChild(script_tag)}if(depends)depends.then(function(){appendScript()});else appendScript();return deferred.promise()}
function addCssRef(href){if(jQuery("link[href='"+href+"']").length)return;var link_tag=document.createElement("link");link_tag.type="text/css";link_tag.rel="stylesheet";link_tag.href=href;var deferred=$.Deferred();link_tag.onload=function(){deferred.resolve()};document.getElementsByTagName("head")[0].appendChild(link_tag);return deferred.promise()}function addInlineStyles(styles,id){if(id&&document.getElementById(id))return;var styleTag=document.createElement("style");styleTag.type="text/css";if(id)styleTag.id=
id;var rules=document.createTextNode(styles);if(styleTag.styleSheet)styleTag.styleSheet.cssText=rules.nodeValue;else styleTag.appendChild(rules);document.getElementsByTagName("head")[0].appendChild(styleTag)}};
